### ISSUE TITLE
Peer review - June 20th

### ISSUE THREAD

**Issue by hajnaloltyan** [ITurres/Task-Manager#10] opened 2023-06-20 15:38 UTC
### Overall super organised and well named file structure, and efficient code. Amazing system to learn from. Keep it up and happy coding! 👏👏👏👏👏

**Suggestions:** 

* @hajnaloltyan : It would be beneficial to be more specific when you're testing the Clear All Button, so like checking if that 1 array element actually has the completed set as false, or matches the desciption of the expected task's description to be left in the array in this case.

* @NitBravoA92 : It's a personal preference, but adding more comments would help to make things more understandable or descriptive.

* @grauJavier : Want to highlight that using afterEach is a very clever solution. In my opinion, using mock functions would be more useful than creating a new file with copied function in it, and also there are different ways to mock for example a 'click', by setting an input field's value directly. You can use different tricks, and be smart about testing, like another way would be to add the **__testmode__** variable, to encapsulate relevant code block for testing in an 'if' statement.

**Comment by ITurres** [comment] 2023-06-21 13:41
### Hi Team! Thank you for your valuable feedback on this new issue 🎯!

- We appreciate your input regarding the `Clear all completed` `Jest` test. We will thoroughly review it to identify areas for improvement✍🏼.

- Regarding comments, as discussed in our previous meeting, it is essential to add comments only when necessary to clarify the "why" behind certain code approaches. The "what" should be self-explanatory through clear variable names, functions, iterators, and statements.

- We have decided to create a duplicate of the function for several reasons. Firstly, this approach enables us to preserve the integrity of the original production function by keeping it separate from the testing environment. Secondly, we found it necessary to make a minor modification to the function to ensure its proper functionality when tested. In future projects, we will prioritize Test-Driven Development (TDD) to ensure the creation of testable functions. To compare both functions and observe the differences, you can refer to the following location:

- #### 📁\*\* js/markup-injectors/

    - 📄\* update-tasklist-dom-injection.js `Line 6`
   
- #### 📁\*\* Jest/    

    - 📄\* injectFullTaskListOnDOM.js

 - However, we are committed to continuous learning and implementing best practices to ensure optimal approaches. In this regard, we recognize the value of utilizing **Jest Mocks** as an excellent and better approach and will duly consider its application.

#### Thank you again and happy coding! 👨🏼‍💻😃👩🏼‍💻

**Closed as completed** 2023-08-11 03:37 UTC
Labels: Peer2Peer-Code_Review
